"""rename order_index to position

Revision ID: 1f08d15230bc
Revises: 827f72161f9c
Create Date: 2025-11-09 12:40:38.784056

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1f08d15230bc"
down_revision = "827f72161f9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roadmap_steps", sa.Column("title", sa.String(length=200), nullable=False)
    )
    op.add_column("roadmap_steps", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("roadmap_steps", sa.Column("position", sa.Integer(), nullable=False))
    op.add_column(
        "roadmap_steps", sa.Column("estimated_hours", sa.Float(), nullable=True)
    )
    op.add_column("roadmap_steps", sa.Column("resources", sa.Text(), nullable=True))
    op.add_column(
        "roadmap_steps",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "roadmap_steps",
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.drop_index("ix_roadmap_steps_order_index", table_name="roadmap_steps")
    op.create_index(
        op.f("ix_roadmap_steps_position"), "roadmap_steps", ["position"], unique=False
    )
    op.drop_column("roadmap_steps", "order_index")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "roadmap_steps",
        sa.Column("order_index", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_roadmap_steps_position"), table_name="roadmap_steps")
    op.create_index(
        "ix_roadmap_steps_order_index", "roadmap_steps", ["order_index"], unique=False
    )
    op.drop_column("roadmap_steps", "updated_at")
    op.drop_column("roadmap_steps", "created_at")
    op.drop_column("roadmap_steps", "resources")
    op.drop_column("roadmap_steps", "estimated_hours")
    op.drop_column("roadmap_steps", "position")
    op.drop_column("roadmap_steps", "description")
    op.drop_column("roadmap_steps", "title")
    # ### end Alembic commands ###
