"""add template_id to roadmaps

Revision ID: c149b1341c36
Revises: 1f08d15230bc
Create Date: 2025-11-09 13:06:25.643199

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c149b1341c36"
down_revision = "1f08d15230bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roadmap_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("structure", sa.JSON(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("roadmaps", sa.Column("template_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None,
        "roadmaps",
        "roadmap_templates",
        ["template_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roadmaps", type_="foreignkey")
    op.drop_column("roadmaps", "template_id")
    op.drop_table("roadmap_templates")
    # ### end Alembic commands ###
